# **19CSE305: MACHINE LEARNING LAB 2**

PYTHON BASICS : EXCERCISES

ROLL NUMBER: CB.EN.U4CSE19056

In [ ]:
PYTHON BASIC EXCERSISE

1)Get two positive integers start and end from the user and write a Python program to print all Prime numbers in that Interval.
2) Given a list of strings( Entered by the user), write program to get a percentage share of each word in the strings list.
percentage := (Occurrence of a word / Total words) * 100
3)Check if  given number is Fibonacci number or not. Given an integer ‘n’( Entered by the user), write a Python function that returns true if n  is Fibonacci number else return false.
4)Write a program to check if all digits of a number divide it. Given a number n( Entered by the user), find whether all digits of n divide it or not.
5)Get a given array as input from the user and split it from a specified position, and move the first part of array add to the end.
example:
Input : {1, 2, 3, 4, 5}, k = 3
Output :{4,5,1,2,3}


NUMPY BASIC EXCERSISE

1) Create a 2D array of shape 4x5 that contains random decimal numbers between 3 and 10.
2) Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3) Given a NumPy array of temperature values, convert the values of Fahrenheit degrees into Centigrade degrees. 
4) Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5) Write a NumPy program to extract third and fourth elements of the second and third rows from a given (3x4) array.



# NUMPY BASIC EXERCISE

In [4]:
#1)
import numpy as np
rand_arr = np.random.uniform(3,10, size=(4,5))
print(rand_arr)

[[3.54555619 9.30318703 8.79702214 6.21433425 7.27407144]
 [7.40041073 6.51809613 4.49310132 3.7095533  8.23374772]
 [7.30840871 6.09928186 9.03832393 5.06071489 4.18882958]
 [8.27269297 9.17615817 7.81015275 9.20476512 8.18226516]]


In [7]:
#2)
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
#3
ftemp=np.array([69,4,20,50,100])

for i in range(len(ftemp)):
    ftemp[i]=((ftemp[i]-32)*5)/9  
    
print(ftemp)   

[ 20 -15  -6  10  37]


In [21]:
#4
print(ftemp.ndim)
print(ftemp.size)
print(ftemp.itemsize)

1
5
4


In [30]:
#5
a=np.array([[4,4,2,1],[4,2,0,1],[6,9,2,1]])
print(a.shape)
print(a[1:,2:])

(3, 4)
[[0 1]
 [2 1]]


# Python Basic

In [33]:

#1
a = int(input())  
b = int(input())  
  
for num in range(a,b + 1):  
   if num > 1:  
       for i in range(2,num):  
           if (num % i) == 0:  
               break  
       else:  
           print(num)  
    

2
100
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [36]:
#3
import math
 
def isPerfectSquare(x):
    s = int(math.sqrt(x))
    return s*s == x
 
def isFibonacci(n):
 
    return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4)
    
a=int(input())
print(isFibonacci(a))

8
True


In [37]:
#4
def checkDivisibility(n, digit) :
    
    return (digit != 0 and n % digit == 0)

def allDigitsDivide( n) :
     
    temp = n
    while (temp > 0) :
         
        
        digit = temp % 10
        if ((checkDivisibility(n, digit)) == False) :
            return False
 
        temp = temp // 10
     
    return True
 

n=int(input())
 
if (allDigitsDivide(n)) :
    print("Yes")
else :
    print("No" )
     

128
Yes
